[package]
name = "avr-int24"
version = "0.1.0"
authors = [ "Michael Buesch <m@bues.ch>" ]
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]

[lints.clippy]
undocumented_unsafe_blocks = "warn"
